"""

    COVID-19
    Project : college
    A project for students about the school reopening
     - how many students should come
     - in which batch
     - at what timing


   1. Add all the students first
   2. Make a file
"""

class Student:
    def __init__(self, name, roll, age, standard, phone, gender):
        self.name = name
        self.roll = roll
        self.age = age
        self.standard = standard
        self.phone = phone
        self.gender = gender


    # user defined function -> csv -> comma separated version
    def to_csv(self):
        return "{name},{roll},{age},{standard},{phone},{gender}\n".format_map(vars(self))


    # another way to write in a file
    # using a function to write in "new_file"
    # It will be written in a class and the other method will be written in main function
    def save(self):
        data = self.to_csv()
        file = open("new_file","a")    # "a" -> append the data in a file
        file.write(data)
        # choice = input("Would You Like to Save {}: (yes/no) ".format(self.name))
        # if choice == "yes":
        #     file.write(data)
        #     print("Data Saved :)")
        # else:
        #     print(data)

def main():
    # object
    student1 = Student(
        name = "john",
        roll= 1,
        age=10,
        standard=5,
        phone= "+91 99999 11111",
        gender="male"
    )
    student2 = Student(
        name = "fionna",
        roll= 2,
        age=12,
        standard=7,
        phone= "+91 99999 22222",
        gender="female"
    )
    student3 = Student(
        name="jack",
        roll=3,
        age=10,
        standard=6,
        phone="+91 99999 33333",
        gender="male"
    )


    # calling the save function with class student objects

    student1.save()
    student2.save()
    student3.save()


# SERIALIZATION -> When we save the state of an object in file

""" 
This is also a way to write in a file 
It will be written in the main method

   # with this line of code, a new file is generated by the name new_file and "w" represents that we are
    # writing in a file, and if we change the object which is assigned to data,it will remove the previous
    # object details
    file = open("new_file", "w")

    # "a" -> appending in the file
    # this will not remove the previous data , it will the new object data and the previous one  remains same
    # file = open("new_file", "a")

    # calling to_csv function with student2 object and assigning it's teference to variable "data"
    data = student2.to_csv()

    # this line will write the data in the new_file and it takes string as an arguement not anything else
    file.write(data)
    """







if __name__ == '__main__':
    main()
